services:
  # catalog:
  #   container_name: catalog
  #   build:
  #     context: ./apps/gamestore-games-catalog
  #   env_file:
  #     - '.env'
  #   ports:
  #     - '${GAMESTORE_GAMES_CATALOG_PORT}:${GAMESTORE_GAMES_CATALOG_PORT}'
  #   command: pnpm run start:dev
  #   depends_on:
  #     - mysql
  #   restart: always
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql_container:/var/lib/mysql
    environment:
      MYSQL_DATABASE: db
      MYSQL_PASSWORD: 1111
      MYSQL_ROOT_PASSWORD: 1111

volumes:
  mysql_container:
    driver: local
